version: '3.8'

services:
  dotnetapp:
    image: backend:latest
    container_name: dotnetapp
    ports:
      - "5001:80"
    networks:
      - app-network

  nodejsapp:
    image: front:latest
    container_name: nodejsapp
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dotnetapp
      - nodejsapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
