//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSMSearch.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LsmTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public LsmTestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSMSearch.Tests.LsmTestsResources", typeof(LsmTestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;buildings&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;0cccab2b-bc8d-44c5-b248-8a9ca6d7e899&quot;,
        ///      &quot;shortCut&quot;: &quot;HOFF&quot;,
        ///      &quot;name&quot;: &quot;Head Office&quot;,
        ///      &quot;description&quot;: &quot;Head Office, Feringastraße 4, 85774 Unterföhring&quot;
        ///    }
        ///  ],
        ///  &quot;locks&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;0a1e6f38-6076-4da8-8d6c-87356f975baf&quot;,
        ///      &quot;buildingId&quot;: &quot;0cccab2b-bc8d-44c5-b248-8a9ca6d7e899&quot;,
        ///      &quot;type&quot;: &quot;Cylinder&quot;,
        ///      &quot;name&quot;: &quot;Gästezimmer 4.OG&quot;,
        ///      &quot;description&quot;: null,
        ///      &quot;serialNumber&quot;: &quot;UID-A89F98F3&quot;,
        ///      &quot;floor&quot;: &quot;4.OG&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Data_OneBuilding_10RelatedLocks {
            get {
                return ResourceManager.GetString("Data_OneBuilding_10RelatedLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;buildings&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;0cccab2b-bc8d-44c5-b248-8a9ca6d7e899&quot;,
        ///      &quot;shortCut&quot;: &quot;HOFF&quot;,
        ///      &quot;name&quot;: &quot;Head Office&quot;,
        ///      &quot;description&quot;: &quot;Head Office, Feringastraße 4, 85774 Unterföhring&quot;
        ///    }
        ///  ],
        ///  &quot;locks&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;0a1e6f38-6076-4da8-8d6c-87356f975baf&quot;,
        ///      &quot;buildingId&quot;: &quot;0cccab2b-bc8d-44c5-b248-8a9ca6d7e899&quot;,
        ///      &quot;type&quot;: &quot;Cylinder&quot;,
        ///      &quot;name&quot;: &quot;Gästezimmer 4.OG&quot;,
        ///      &quot;description&quot;: null,
        ///      &quot;serialNumber&quot;: &quot;UID-A89F98F3&quot;,
        ///      &quot;floor&quot;: &quot;4.OG&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Data_OneBuildingAndTwoRelatedLocks {
            get {
                return ResourceManager.GetString("Data_OneBuildingAndTwoRelatedLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;groups&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;70c886f5-b74e-49f4-8d9f-cf2d6645d4d6&quot;,
        ///          &quot;name&quot;: &quot;&lt;default&gt;&quot;,
        ///          &quot;description&quot;: &quot;Default group where all transponders&quot;
        ///        }
        ///    ],
        ///      &quot;media&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;2c2ec98f-137a-4c49-a47a-814ae18a3364&quot;,
        ///      &quot;groupId&quot;: &quot;70c886f5-b74e-49f4-8d9f-cf2d6645d4d6&quot;,
        ///      &quot;type&quot;: &quot;Card&quot;,
        ///      &quot;owner&quot;: &quot;Gast 1&quot;,
        ///      &quot;description&quot;: null,
        ///      &quot;serialNumber&quot;: &quot;UID-378D17F6&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;1a3648e2-1641-47f5-b9e3-dec74 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Data_OneGroupThreeMedia {
            get {
                return ResourceManager.GetString("Data_OneGroupThreeMedia", resourceCulture);
            }
        }
    }
}
